version: "3.3"
services:
    app_virtuasec:
        container_name: "app_virtuasec"
        build:
            context: .setup/docker/app
            dockerfile: Dockerfile
            args:
                - USER=${USER}
                - UPLOAD=20
        restart: "always"
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/public
        volumes:
            - ./:/var/www
        depends_on:
            - db_virtuasec
        links:
            - db_virtuasec
        ports:
            - "8000:80"

    db_virtuasec:
        container_name: "db_virtuasec"
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=true
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./.setup/docker/db:/var/lib/mysql
